[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
metaplex_nft = "HNyPqG6w1NQTx4gEB4eHGFJNDMQQJibc8LQwJqJ5awoo"
shenqi_box = "2ZgjDLphMVoLT48YCk2ZvAsHpdwkqtkhyCWsjR1Gda7x"
token_2022_nft = "2PLQsLqv33ZAtLh4WA7BCnnXTNsrZEY3QBxhVDx8JZTe"

[programs.localnet]
metaplex_nft = "HNyPqG6w1NQTx4gEB4eHGFJNDMQQJibc8LQwJqJ5awoo"
shenqi_box = "2ZgjDLphMVoLT48YCk2ZvAsHpdwkqtkhyCWsjR1Gda7x"
token_2022_nft = "2PLQsLqv33ZAtLh4WA7BCnnXTNsrZEY3QBxhVDx8JZTe"

[programs.mainnet]
metaplex_nft = "HNyPqG6w1NQTx4gEB4eHGFJNDMQQJibc8LQwJqJ5awoo"
shenqi_box = "2ZgjDLphMVoLT48YCk2ZvAsHpdwkqtkhyCWsjR1Gda7x"
token_2022_nft = "2PLQsLqv33ZAtLh4WA7BCnnXTNsrZEY3QBxhVDx8JZTe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts --reporter mochawesome"
