//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_pubkey::{pubkey, Pubkey};

/// `token2022_nft` program ID.
pub const TOKEN2022_NFT_ID: Pubkey = pubkey!("2PLQsLqv33ZAtLh4WA7BCnnXTNsrZEY3QBxhVDx8JZTe");
